### ISSUE TITLE
Warning from django1.7.7

### ISSUE THREAD

**Issue by weasteam** [jezdez/django-robots#29]
/Library/Python/2.7/site-packages/robots/forms.py:7: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form RuleAdminForm needs updating
  class RuleAdminForm(forms.ModelForm):

**Comment by SalahAdDin** [comment]
Hey, in other issue we explained how fix this issue :D

**Comment by weasteam** [comment]
On which issue? I can not find it.

**Comment by SalahAdDin** [comment]
I try to find it and the put here.

**Comment by tezro** [comment]
This breaks the 1.8 now.

**Comment by SalahAdDin** [comment]
What? What happen now?
