### ISSUE TITLE
Needs version bump and new deploy to PyPi

### ISSUE THREAD

**Issue by ryan-blunden** [jezdez/django-robots#31]
Just pip installed this but it doesn't have the fix for fields fix in robots/forms.py.

I've worked around this by changing the entry in my requirements.txt file to `-e git://github.com/jezdez/django-robots.git#egg=robots` to install it from GitHub.

**Comment by muratcorlu** [comment]
:+1:

**Comment by SalahAdDin** [comment]
:+1:

**Comment by martync** [comment]
Pull request is waiting approval https://github.com/jezdez/django-robots/pull/30

**Comment by vint21h** [comment]
bump

**Comment by martync** [comment]
I'm not used to write "+1" but .... 
+1 for bump

**Comment by jezdez** [comment]
1.1 is out. If you'd like to give something back, feel free to donate something at https://www.djangoproject.com/fundraising/ Thanks!
