### ISSUE TITLE
Django 1.4 compatibility

### ISSUE THREAD

**Issue by WoLpH** [jezdez/django-robots#39]
Unfortunately I'm still stuck with Django 1.4 for one of my projects, and the latest release (1.1) breaks compatibility. The specific thing that breaks it: https://github.com/jezdez/django-robots/commit/41ac348e4f43f9387a28e39fd99bb68bb13634cb

Beyond that it seems to work just fine so it would be great if that setting would be version dependent.

**Comment by jezdez** [comment]
Sorry but 1.4 will be soon not supported upstream anymore, so for now simply use an older version of the app.

**Comment by WoLpH** [comment]
Too bad, guess I'll keep it at 1.0 in that case
